const BASE_URL_SHOPṔING_CART_MICROSERVICE = 'http://localhost:3332';
const BASE_URL_PRODUCT_MICROSERVICE = 'http://localhost:3333';

export const API_URL_MICROSERVICE = {
  SHOPPING_CART: `${BASE_URL_SHOPṔING_CART_MICROSERVICE}/shopping-cart`,
  INSERT_PRODUCT_TO_CART: `${BASE_URL_SHOPṔING_CART_MICROSERVICE}/shopping-cart/product`,
  REMOVE_PRODUCT_FROM_CART: `${BASE_URL_SHOPṔING_CART_MICROSERVICE}/shopping-cart/remove/product/`,
  LIST_PRODUCTS: `${BASE_URL_PRODUCT_MICROSERVICE}/products`,
};
